// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc-FU8W6C55CMohlsxHobWbjiCguDQbyE',
    appId: '1:565764851741:android:acc878be74a36be09a9ef4',
    messagingSenderId: '565764851741',
    projectId: 'mytime-a2832',
    storageBucket: 'mytime-a2832.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjuLYiPamheICBZ5rq88HsleEIrCHLU9o',
    appId: '1:565764851741:web:6856d7059df9556a9a9ef4',
    messagingSenderId: '565764851741',
    projectId: 'mytime-a2832',
    authDomain: 'mytime-a2832.firebaseapp.com',
    storageBucket: 'mytime-a2832.firebasestorage.app',
    measurementId: 'G-CGS8JD23Q1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3CE48dlOFGNCVyWWPEDzE0VRmXwXZ-TQ',
    appId: '1:565764851741:ios:9a37b77ebd9a194a9a9ef4',
    messagingSenderId: '565764851741',
    projectId: 'mytime-a2832',
    storageBucket: 'mytime-a2832.firebasestorage.app',
    iosBundleId: 'com.example.mytime',
  );
}
